# Generated by Django 5.0.7 on 2024-07-26 00:31

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=100, verbose_name='Razon social')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('web_site', models.URLField(blank=True, verbose_name='Sitio web')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Telefono contacto')),
            ],
            options={
                'verbose_name': 'Provedor',
                'verbose_name_plural': 'Provedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('codigo_barras', models.CharField(max_length=10, unique=True, verbose_name='Codigo barras')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre producto')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad stock')),
                ('precio_compra', models.PositiveIntegerField(default=1, verbose_name='Precio de compra')),
                ('precio_venta', models.PositiveIntegerField(default=2, verbose_name='Precio de venta')),
                ('disponible', models.BooleanField(default=True, verbose_name='Producto disponible')),
                ('cantidad_vendida', models.PositiveIntegerField(default=0, verbose_name='Cantidad vendida')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.marca')),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.provedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
