# Generated by Django 5.0.7 on 2024-07-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nombre_completo', models.CharField(max_length=50, verbose_name='Nombre Completo')),
                ('ocupacion', models.CharField(blank=True, choices=[('1', 'Tecnico'), ('2', 'Tecnologo'), ('3', 'Profesional'), ('4', 'Especilista'), ('5', 'Vendedor'), ('6', 'Administrador'), ('7', 'Otro')], max_length=1, verbose_name='Ocupacion')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fehca de Nacimiento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Usuarios', verbose_name='Foto')),
                ('direccion', models.CharField(blank=True, max_length=50, verbose_name='Direccion')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
