# Generated by Django 5.0.7 on 2024-07-26 00:31

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('codigo_barras', models.CharField(max_length=10, unique=True, verbose_name='Codigo de barras')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_carrito', to='producto.producto')),
            ],
            options={
                'verbose_name': 'Carrito de Compra',
                'verbose_name_plural': 'Carrito de Compras',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha_venta', models.DateField(verbose_name='Fecha de Venta')),
                ('cantidad_productos', models.PositiveIntegerField(verbose_name='Cantidad de productos')),
                ('total_venta', models.PositiveIntegerField(verbose_name='Total de la venta')),
                ('anulada', models.BooleanField(default=False, verbose_name='Venta anulada')),
                ('tipo_pago', models.CharField(blank=True, choices=[('0', 'Efectivo'), ('1', 'Tarjeta'), ('2', 'Cheque'), ('3', 'Bono'), ('4', 'Otro')], max_length=1, verbose_name='Tipo de pago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_compra', models.PositiveIntegerField(verbose_name='Precio de compra')),
                ('precio_venta', models.PositiveIntegerField(verbose_name='Precio de venta')),
                ('anulado', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_producto', to='producto.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_ventas', to='venta.venta', verbose_name='Codigo de Venta')),
            ],
            options={
                'verbose_name': 'Detalle Venta',
                'verbose_name_plural': 'Detalle Ventas',
            },
        ),
    ]
